# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0e23e97431ef0b147c39724334ca163b0c684f7961e6684712ac40fd11021c789a900a9413ed5cbaf7c418b5118c804ed3bdd6bfb514640dbbaa513a882f94

test:
  secret_key_base: 4c5ac5711260cb9fca72985e17e0613e0fd4e631706a5b965204495cc7427610eec0345d402366d7f1f147880cb0384a66805cb8d3a3f8f223cd796619aae8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
